import "@repo/ui/globals.css";
import "./globals.css";

import type { PropsWithChildren } from "react";
import type { Metadata } from "next";

import { Inter } from "next/font/google";

import ConvexClientProvider from "@/providers/ConvexClientProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Notepad Webapp",
  description: "Generated by create turbo",
};

function RootLayout({ children }: PropsWithChildren): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}

export default RootLayout;
