// Automatically generated by declarative-routing, do NOT edit
import { z } from "zod";
import { makeRoute } from "./makeRoute";

const defaultInfo = {
  search: z.object({})
};

import * as HomeRoute from "@/app/page.info";
import * as DashboardRoute from "@/app/dashboard/page.info";
import * as DashboardHeaderRoute from "@/app/dashboard/@header/page.info";
import * as DashboardHeaderRecordsRoute from "@/app/dashboard/@header/records/page.info";
import * as DashboardHeaderSettingsRoute from "@/app/dashboard/@header/settings/page.info";
import * as DashboardHeaderTasksRoute from "@/app/dashboard/@header/tasks/page.info";
import * as DashboardRecordsRoute from "@/app/dashboard/records/page.info";
import * as DashboardSettingsRoute from "@/app/dashboard/settings/page.info";
import * as SettingsAppearanceRoute from "@/app/dashboard/settings/appearance/page.info";
import * as DashboardTasksRoute from "@/tasks/page.info";
import * as SigninRoute from "@/app/sign-in/[[...sign-in]]/page.info";
import * as SignupRoute from "@/app/sign-up/[[...sign-up]]/page.info";

export const Home = makeRoute(
  "/",
  {
    ...defaultInfo,
    ...HomeRoute.Route
  }
);
export const Dashboard = makeRoute(
  "/dashboard",
  {
    ...defaultInfo,
    ...DashboardRoute.Route
  }
);
export const DashboardHeader = makeRoute(
  "/dashboard/@header",
  {
    ...defaultInfo,
    ...DashboardHeaderRoute.Route
  }
);
export const DashboardHeaderRecords = makeRoute(
  "/dashboard/@header/records",
  {
    ...defaultInfo,
    ...DashboardHeaderRecordsRoute.Route
  }
);
export const DashboardHeaderSettings = makeRoute(
  "/dashboard/@header/settings",
  {
    ...defaultInfo,
    ...DashboardHeaderSettingsRoute.Route
  }
);
export const DashboardHeaderTasks = makeRoute(
  "/dashboard/@header/tasks",
  {
    ...defaultInfo,
    ...DashboardHeaderTasksRoute.Route
  }
);
export const DashboardRecords = makeRoute(
  "/dashboard/records",
  {
    ...defaultInfo,
    ...DashboardRecordsRoute.Route
  }
);
export const DashboardSettings = makeRoute(
  "/dashboard/settings",
  {
    ...defaultInfo,
    ...DashboardSettingsRoute.Route
  }
);
export const SettingsAppearance = makeRoute(
  "/dashboard/settings/appearance",
  {
    ...defaultInfo,
    ...SettingsAppearanceRoute.Route
  }
);
export const DashboardTasks = makeRoute(
  "/dashboard/tasks",
  {
    ...defaultInfo,
    ...DashboardTasksRoute.Route
  }
);
export const Signin = makeRoute(
  "/sign-in/[[...sign-in]]",
  {
    ...defaultInfo,
    ...SigninRoute.Route
  }
);
export const Signup = makeRoute(
  "/sign-up/[[...sign-up]]",
  {
    ...defaultInfo,
    ...SignupRoute.Route
  }
);

